version: 2.1
orbs:
    gh: circleci/github-cli@1.0.3
jobs:
    build:
        docker:
            - image: cimg/node:18.17.0-browsers
        steps:
            - checkout
            - restore_cache:
                key: v1-dependencies--{{ checksum "package.json" }}--{{ checksum "symbols-mui/package.json" }}
            - run:
                  name: Install Dependencies
                  command: |
                      yarn install
                      cd symbols-mui && yarn install:dependencies
            - run:
                  name: Build Packages
                  command: |
                      yarn build
                      cd symbols-mui && yarn build
            - run:
                  name: Verify SVG Build Artifacts
                  command: |
                      yarn test:svg
                      cd symbols-mui && yarn test
            - save_cache:
                  name: Save Cache
                  paths:
                    - node_modules
                    - icons-mui/node_modules
                  key: v1-dependencies--{{ checksum "package.json" }}--{{ checksum "symbols-mui/package.json" }}
            - persist_to_workspace:
                  root: .
                  paths:
                    - symbols
                    - symbols-mui/symbols

    publish:
      docker:
        - image: cimg/node:18.17.0-browsers
      steps:
        - checkout
        - attach_workspace:
            at: .
        - run:
            name: Authenticate with registry
            command:  |
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
              echo "//registry.yarnpkg.com/:_authToken=$NPM_TOKEN" >> ~/.npmrc
        - run:
            name: Publish @brightlayer-ui/symbols
            command: cd symbols && yarn publish:package -b $CIRCLE_BRANCH
        - run:
            name: Publish @brightlayer-ui/symbols-mui
            command: cd symbols-mui && yarn publish:package -b $CIRCLE_BRANCH
    tag:
      docker:
        - image: cimg/node:18.17.0-browsers
      steps:
        - checkout
        - gh/setup
        - attach_workspace:
            at: .
        - run:
            name: Tag @brightlayer-ui/symbols
            command: cd symbols && yarn tag:package -b $CIRCLE_BRANCH -s -blui-symbols
        - run:
            name: Tag @brightlayer-ui/symbols-mui
            command: cd symbols-mui && yarn tag:package -b $CIRCLE_BRANCH -s -blui-symbols-mui
workflows:
  version: 2
  symbols:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - dev
      - tag:
          requires:
            - publish
          filters:
            branches:
              only:
                - master
